// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVJgeq0e39azS9J8bKg6Yfans3cxSTncA',
    appId: '1:817093154101:web:91c906a54e4cf015cb287c',
    messagingSenderId: '817093154101',
    projectId: 'unibite-fb2e4',
    authDomain: 'unibite-fb2e4.firebaseapp.com',
    storageBucket: 'unibite-fb2e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp-9nyUc4yw9gZIiRIgiwRFEubbpXuHS8',
    appId: '1:817093154101:android:78bcabb81fdcc546cb287c',
    messagingSenderId: '817093154101',
    projectId: 'unibite-fb2e4',
    storageBucket: 'unibite-fb2e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhUunsOzj_yqN-DiRgLTifVmU3IVaaWfk',
    appId: '1:817093154101:ios:15998efc63b9e566cb287c',
    messagingSenderId: '817093154101',
    projectId: 'unibite-fb2e4',
    storageBucket: 'unibite-fb2e4.firebasestorage.app',
    iosBundleId: 'com.example.unibite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhUunsOzj_yqN-DiRgLTifVmU3IVaaWfk',
    appId: '1:817093154101:ios:15998efc63b9e566cb287c',
    messagingSenderId: '817093154101',
    projectId: 'unibite-fb2e4',
    storageBucket: 'unibite-fb2e4.firebasestorage.app',
    iosBundleId: 'com.example.unibite',
  );
}
